name: CMake Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Generate makefiles
        run: cmake .

      - name: Compile app
        run: make

      - name: Run app
        run: ./untitled